:art: Update JSDoc Grunt task implementation
These changes do the following:

- the `grunt doc` task fails on machine with NPM 3 installed - or just
always when flattened NPM modules structure is used. This is because the
Grunt plugin for JSDoc assumed the nested modules structure
- The fix to the failing task is to install updated Grunt JSDoc plugin (check)
- Install additional template NPM module used by this library (check)
- update Grunt task configuration to use a path for template that will work with
flattened and nested structure of modules.

The commit allows to move from an error like this:
```bash
grunt doc
Running "jsdoc:dist" (jsdoc) task
>> An error occurs in jsdoc process:
>> js: "/Users/piotrblazejewicz/git/azure-storage-node/node_modules/jsdoc/jsdoc.js",
line 316: exception from uncaught JavaScript throw: Error: Module "taffydb" not found.
Warning: jsdoc failure Use --force to continue.

Aborted due to warnings.
```
```bash
grunt doc
Running "jsdoc:dist" (jsdoc) task
>> FATAL: Unable to load template: Cannot find module
node_modules/grunt-jsdoc/node_modules/ink-docstrap/template/publish
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.
```
to successful JSDoc generation with Grunt task:
```bash
grunt doc
Running "jsdoc:dist" (jsdoc) task
>> Documentation generated to /Users/piotrblazejewicz/git/azure-storage-node/docs

Running "devserver:server" (devserver) task
starting server on 8888
listening on 8888
```

Thanks!